name: CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # - uses: actions/setup-python@v5
        #   with:
        #     python-version: 3.11.x
        #     cache: pip
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v3
        # - uses: docker/setup-buildx-action@v3
        #       - name: Check python
        #         run: python scripts/deploy_utils.py image_tag
      - name: Initialize terraform
        run: terraform -chdir=infra init
      - name: Check state (sanity check)
        run: terraform -chdir=infra state list
      - name: Store Terraform outputs
        id: tfout
        run: terraform -chdir=infra output -json
          #      - name: Check docker
          #        run: docker run hello-world
      - name: Try out terraform output
        run: |
          echo ${{ fromJson(steps.tfout.outputs.stdout).app_uri.value }}
          echo ${{ fromJson(steps.tfout.outputs.stdout).docker_tag_base.value }}
