name: 'Continuous Integration'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.x
          cache: pip
      - name: Pre-commit cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ runner.os }}|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install pre-commit
        run: pip install pre-commit -c requirements.txt
      - name: Run pre-commit on all files
        run: pre-commit run --show-diff-on-failure --color=always --all-files
  python-changes:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    outputs:
      value: ${{ steps.filter.outputs.challenge || steps.filter.outputs.tests }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'challenge/**/*.py'
            tests:
              - 'tests/**/*.py'
  types:
    runs-on: ubuntu-latest
    needs: python-changes
    if: ${{ !github.event.pull_request.draft  &&  needs.python-changes.outputs.value }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.x
          cache: pip
      - name: Install Mypy
        run: pip install '.[test,types]' -c requirements.txt
      - name: Run Mypy
        run: mypy challenge tests
